### ISSUE TITLE
no error or redirect to NotFound if journey doesn't exist

### ISSUE THREAD

**Issue by EinSev** [JourneyPlanner/JourneyPlanner-old#105]
For example there isn't a journey at [https://journeyplanner.io/reise/321c2523-78ee-4f](https://journeyplanner.io/reise/321c2523-78ee-4f), but you could still access this site and the components would try to load the data but because the journey doesn't exist they can't load, instead of redirecting to the not-found/error page.

**Comment by Mathematti** [comment]
Does this also apply to journeys that exist but that you aren't a part of?

**Comment by EinSev** [comment]
> Does this also apply to journeys that exist but that you aren't a part of?

Yes
